### ISSUE TITLE
murr_front-dev

### ISSUE THREAD

**Issue by Murrengan** [Murrengan/murr#157]
1) https://github.com/Murrengan/murr/blob/murr_front/src/main.js#L11
Обычно ничего напрямую в main.js не пишется. Лучше вынести все в отдельный файл.
Сторонки например вот сюда унеси murr/src/store/index.js

2) https://github.com/Murrengan/murr/blob/murr_front/src/MurrApp.vue
Вот тут тоже должен быть скорее всего <router-view/>, а компонент внутри будет такой, который связан с URL текущим

3) v-on:click => @click

4) import {mapGetters} from 'vuex'
import {mapActions} from 'vuex'
=> import {mapActions, mapGetters}from 'vuex’;

5) .pop_up_container { => вот тут что-то не так, должен быть скорее всего display: flex и все к нему относящиеся

6) SignUp.vue => вот тут попробуй избавится от watch, это довольно большая нагрузка для приложения, если их будет потом много

7) this.$store.commit('auth/AUTHENTICATE'); Вот такое тоже не используй (this.$store). Есть специальные хелперы типа
const {
  mapGetters,
  mapActions
} = createNamespacedHelpers(‘auth’);

**Comment by jKEeY** [comment]
Хочу немного выразить не довольствие на счёт mapGetters mapActions

1.  Getters вообще мало где применимы и не желательно их использовать в качестве просто доставания данных из сторы, если ты не собираешься их мутировать как либо, если ты просто обращаешься к сторе и достаешь с помощью геттеров данные, то лучше всего использовать в компонентах mapState

`
import { mapState } from 'vuex'
computed: {
    ...mapState({
          isAuth: state => state.nameModule.auth
    })
}
`
2. Вместо назойливого mapActions можно обращаться на прямую через глобальный объект this.$store
Только в случае, когда ты пытаешься обращаться к методу dispatch, нужно в конце приписывать { root: true } (**Это рекомендации Разработчика Vuex**)

`this.$store.dispatch('module/name', null, { root: true }) //Если у нас нет передаваемого параметра в action`
`this.$store.dispatch('module/name',{ title: 'Hello' }, { root: true })  // Если параметр передаётся`

_Вот пример_

![Screen Shot 2020-01-13 at 20 00 04](https://user-images.githubusercontent.com/36997266/72275681-71e69d80-363f-11ea-8a8b-70d1ca17f7c2.png)

**Comment by jKEeY** [comment]
Это всё избавит от лишнего кода

**Comment by Murrengan** [comment]
Вынести общие данные (вход, регистрация) как компоненты - импортировать их и использовать как темплейты <название_компонента>

**Comment by jKEeY** [comment]
### Хочу немного рассказать про компоненты
Они бывают: умные или глупые

_Умные компоненты:_ 
1.оборачивает один или несколько глупых или умных компонентов 
2. хранит состояние стора и пробрасывает его как объекты в глупые компоненты
3. никогда не имеют собственных стилей
4. редко сами выдают DOM, используйте глупые компоненты для макета
5. имеры: UserPage, FollowersSidebar, StoryContainer, FollowedUserList

Глупые компоненты:
1. не зависят от остальной части приложения, например store
2. часто содержатся в slots
3. имеют свои css стили
4. изредка имеют свой state
5. могут использовать другие глупые компоненты
примеры: Page, Sidebar, Story, UserInfo, List

**Профит от разделения компонентов**
1. Лучшее разделение ответственности. Вы понимаете Ваше приложение и Ваш UI лучше, если пишете компоненты таким способом.
2. Лучшая реюзабельность (переиспользование). Вы можете использовать один и тот же глупый компонент с абсолютно разными источниками состояния.
3. Глупые компоненты — это фактически «палитра» Вашего приложения, Вы можете поместить их все на одну страницу и дать дизайнеру их настроить, на залезая в логику приложения. Вы можете запустить регрессивное тестирование на такой странице.
4. то заставляет Вас извлекать «компоненты макеты», такие как Sidebar, Page, ContextMenu и использовать slots вместо дублирования одной и той же верстки в различных умных компонентах.

**Comment by jKEeY** [comment]
**Пример глупого компонента**
Это просто пример компонента Button.vue
![Screen Shot 2020-01-14 at 14 39 31](https://user-images.githubusercontent.com/36997266/72341607-b7f13f00-36db-11ea-8ac7-af95f88dda76.png)

Вот умный компоненты
![Screen Shot 2020-01-14 at 14 46 31](https://user-images.githubusercontent.com/36997266/72342011-b4aa8300-36dc-11ea-918f-9ace29ee1c98.png)


В первом случае я могу назвать глупый компонент, потому что:
1) Он зависит от props, который передал нам Родитель, и не зависит от store
2) Изолирован от внешнего мира и может быть переиспользован

Мы его можем использовать в разных цветах и передавать разные текста (исходя из примера) 

_А второй пример у нас зависим_

P.S
[Что такое props](https://ru.vuejs.org/v2/guide/components-props.html)
[Что такое slots](https://ru.vuejs.org/v2/guide/components-slots.html)
