### ISSUE TITLE
README.md нехватает описания сути проекта.

### ISSUE THREAD

**Issue by sur0g** [Murrengan/murr#50]
Мне, как непосвященному, не понятно, что из себя представляет проект. Чтобы понять, что разрабатывается, необходимо будет просматривать стримы. Надо более детально расписать назначение проекта.

**Comment by Murrengan** [comment]
То, что есть сейчас, не достаточно?
Социальная сеть, где люди помогают друг другу в достижении поставленных целей.
Как бы ты описал проект?

**Comment by Murrengan** [comment]
> Мне, как непосвященному, не понятно, что из себя представляет проект. Чтобы понять, что разрабатывается, необходимо будет просматривать стримы. Надо более детально расписать назначение проекта.

То, что есть сейчас, не достаточно?
Социальная сеть, где люди помогают друг другу в достижении поставленных целей.
Как бы ты описал проект?
